### PR TITLE
Feature/add php cs fixer

### LINKED ISSUE #95: php-cs-fixer
@DeepDiver1975 
Any plans to implement ``php-cs-fixer`` as we have in core ?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #95

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@patrickjahns now using tooly just to see how this behaves ..... I like it better compared to compposer-bin .... let's decide once you are back ....

**Comment by phil-davis** [comment]
@DeepDiver1975 @patrickjahns where is this heading?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 @patrickjahns where is this heading?

I had a chat with @patrickjahns last week - we will stick to composer-bin

feel free to hijack this PR and adapt. THX

**Comment by DeepDiver1975** [comment]
doesn't work -> bomb

**Comment by phil-davis** [comment]
PR #106 did it

**Pull request closed without merging**
